import { Button, Input } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import { IResponse } from "../interface/IResponse";
import { SendForm } from "../api/sendForm";
import styles from "../styles/Home.module.css";
import { Heading } from "./components/Heading";
import { SubmitMessage } from "./components/SubmitMessage";

const Home: NextPage = () => {
  const [email, setEmail] = useState<string>("");
  const [responseData, setResponseData] = useState<IResponse | null>(null);

  const sendForm = async () => {
    const res = await new SendForm(email).send({ body: { email: email } });
    setResponseData(res);
  };

  const onInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    setEmail((e.target as HTMLInputElement).value);
  };

  const onEnterPress = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      e.preventDefault();
      sendForm();
    }
  };

  const onSubmit = (
    e: React.MouseEvent<HTMLButtonElement> | React.FormEvent<HTMLFormElement>
  ) => {
    e.preventDefault();
    sendForm();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <Heading component={'h3'} content={'Eager to share your views about the workshops?'}/>
        <Heading component={'h5'} content={'Provide your email in the field below to receive a short survey:'}/>
          <form
            className={styles.form}
            method="POST"
            onSubmit={(e) => onSubmit(e)}
          >
            <Input
              sx={{
                my: 2,
                textAlign: "center",
                height: "3rem",
                minWidth: "20rem",
                borderRadius: "0.5rem",
              }}
              onKeyPress={(e: React.KeyboardEvent<HTMLInputElement>) =>
                onEnterPress(e)
              }
              onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                onInput(e)
              }
              id="email"
              value={email}
              type="text"
              placeholder="Enter your email..."
            ></Input>
            <Button size="large" onClick={(e) => onSubmit(e)}>
              SUBMIT
            </Button>
          </form>
          <SubmitMessage responseData={responseData}/>
      </main>
    </div>
  );
};

export default Home;
